workspace:
  base: /go/src
  path: github.com/go-ggz/ggz

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: appleboy/golang-testing:1.9.1
    group: testing
    commands:
      - cp .env.example .env
      - make embedmd
      - make fmt-check
      - make misspell-check
      # - make stylesheets-check

  vendor:
    image: appleboy/golang-testing:1.9.1
    group: testing
    commands:
      - make test-vendor

  test:
    image: appleboy/golang-testing:1.9.1
    group: testing
    commands:
      - coverage all

  build:
    image: appleboy/golang-testing:1.9.1
    group: build
    commands:
      - make docker_build
      - make upx
      - make tar

  codecov:
    image: robertstettner/drone-codecov
    group: build
    secrets: [ codecov_token ]
    files:
      - .cover/coverage.txt
    when:
      event: [ push, pull_request ]

  release:
    image: appleboy/golang-testing:1.9.1
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false

  publish_server:
    image: plugins/docker
    pull: true
    repo: goggz/ggz
    secrets: [ docker_username, docker_password ]
    default_tags: true
    when:
      event: [ push, tag ]
      local: false

  publish_alpine:
    image: plugins/docker
    pull: true
    repo: goggz/ggz
    dockerfile: Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    default_tags: true
    default_suffix: nanoserver
    when:
      event: [ push, tag ]
      local: false

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
