workspace:
  base: /go/src
  path: github.com/go-ggz/ggz

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang:1.11
    pull: true
    environment:
      - GO111MODULE=on
    commands:
      - cp .env.example .env
      - make embedmd
      - make fmt-check
      - make misspell-check

  test:
    image: golang:1.11
    pull: true
    group: testing
    environment:
      - TAGS="bindata sqlite"
      - GO111MODULE=on
    commands:
      - make unit-test-coverage

  generate-coverage:
    image: golang:1.11
    pull: true
    environment:
      - GO111MODULE=on
    commands:
      - make coverage
    when:
      event: [ push, pull_request ]

  build_linux_amd64:
    image: golang:1.11
    pull: true
    group: build
    environment:
      - TAGS=sqlite
      - GO111MODULE=on
    commands:
      - SERVICE=ggz-server make build_linux_amd64
      - SERVICE=ggz-redirect make build_linux_amd64

  build_linux_i386:
    image: golang:1.11
    pull: true
    group: build
    environment:
      - TAGS=sqlite
      - GO111MODULE=on
    commands:
      - SERVICE=ggz-server make build_linux_i386
      - SERVICE=ggz-redirect make build_linux_i386

  build_linux_arm64:
    image: golang:1.11
    pull: true
    group: build
    environment:
      - TAGS=sqlite
      - GO111MODULE=on
    commands:
      - SERVICE=ggz-server make build_linux_arm64
      - SERVICE=ggz-redirect make build_linux_arm64

  build_linux_arm:
    image: golang:1.11
    pull: true
    group: build
    environment:
      - TAGS=sqlite
      - GO111MODULE=on
    commands:
      - SERVICE=ggz-server make build_linux_arm
      - SERVICE=ggz-redirect make build_linux_arm

  codecov:
    image: robertstettner/drone-codecov
    group: build
    secrets: [ codecov_token ]
    files:
      - coverage.all
    when:
      event: [ push, pull_request ]

  release:
    image: golang:1.11
    pull: true
    environment:
      - GO111MODULE=on
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false

  publish_linux_amd64:
    image: plugins/docker
    group: release
    pull: true
    repo: goggz/ggz-server
    dockerfile: dockerfile/server/Dockerfile
    secrets: [ docker_username, docker_password ]
    default_tags: true
    when:
      event: [ push, tag ]
      local: false

  publish_alpine:
    image: plugins/docker
    group: release
    pull: true
    repo: goggz/ggz-server
    dockerfile: dockerfile/server/Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    default_tags: true
    default_suffix: alpine
    when:
      event: [ push, tag ]
      local: false

  publish_linux_i386:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: goggz/ggz-server
    auto_tag: true
    auto_tag_suffix: i386
    dockerfile: dockerfile/server/Dockerfile.i386
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: goggz/ggz-server
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: dockerfile/server/Dockerfile.arm64
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: goggz/ggz-server
    auto_tag: true
    auto_tag_suffix: arm
    dockerfile: dockerfile/server/Dockerfile.arm
    when:
      event: [ push, tag ]
      local: false

  publish_linux_amd64_redirect:
    image: plugins/docker
    group: release
    pull: true
    repo: goggz/ggz-redirect
    dockerfile: dockerfile/redirect/Dockerfile
    secrets: [ docker_username, docker_password ]
    default_tags: true
    when:
      event: [ push, tag ]
      local: false

  publish_alpine_redirect:
    image: plugins/docker
    group: release
    pull: true
    repo: goggz/ggz-redirect
    dockerfile: dockerfile/redirect/Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    default_tags: true
    default_suffix: alpine
    when:
      event: [ push, tag ]
      local: false

  publish_linux_i386_redirect:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: goggz/ggz-redirect
    auto_tag: true
    auto_tag_suffix: i386
    dockerfile: dockerfile/redirect/Dockerfile.i386
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm64_redirect:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: goggz/ggz-redirect
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: dockerfile/redirect/Dockerfile.arm64
    when:
      event: [ push, tag ]
      local: false

  publish_linux_arm_redirect:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: goggz/ggz-redirect
    auto_tag: true
    auto_tag_suffix: arm
    dockerfile: dockerfile/redirect/Dockerfile.arm
    when:
      event: [ push, tag ]
      local: false

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
