---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.12
  commands:
  - make vet
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: lint
  pull: always
  image: golang:1.12
  commands:
  - make lint
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: misspell
  pull: always
  image: golang:1.12
  commands:
  - make misspell-check
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: embedmd
  pull: always
  image: golang:1.12
  commands:
  - make embedmd
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: test
  pull: always
  image: golang:1.12
  commands:
  - make test
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: codecov
  pull: always
  image: robertstettner/drone-codecov
  settings:
    token:
      from_secret: codecov_token

volumes:
- name: gopath
  temp: {}

---
kind: pipeline
name: ggz-server-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_COMMIT_SHA:0:8} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/amd64/ggz-server ./cmd/ggz-server"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_TAG##v} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/amd64/ggz-server ./cmd/ggz-server"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.12
  commands:
  - ./release/linux/amd64/ggz-server --help

- name: dryrun
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    cache_from: goggz/ggz-server
    dockerfile: docker/ggz-server/Dockerfile.linux.amd64
    dry_run: true
    repo: goggz/ggz-server
    tags: linux-amd64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    cache_from: goggz/ggz-server
    daemon_off: false
    dockerfile: docker/ggz-server/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: goggz/ggz-server
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: ggz-server-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build-push
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_COMMIT_SHA:0:8} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm64/ggz-server ./cmd/ggz-server"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_TAG##v} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm64/ggz-server ./cmd/ggz-server"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.12
  commands:
  - ./release/linux/arm64/ggz-server --help

- name: dryrun
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    cache_from: goggz/ggz-server
    dockerfile: docker/ggz-server/Dockerfile.linux.arm64
    dry_run: true
    repo: goggz/ggz-server
    tags: linux-arm64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    cache_from: goggz/ggz-server
    daemon_off: false
    dockerfile: docker/ggz-server/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: goggz/ggz-server
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: ggz-server-linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: build-push
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_COMMIT_SHA:0:8} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm/ggz-server ./cmd/ggz-server"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_TAG##v} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm/ggz-server ./cmd/ggz-server"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.12
  commands:
  - ./release/linux/arm/ggz-server --help

- name: dryrun
  pull: always
  image: plugins/docker:linux-arm
  settings:
    cache_from: goggz/ggz-server
    dockerfile: docker/ggz-server/Dockerfile.linux.arm
    dry_run: true
    repo: goggz/ggz-server
    tags: linux-arm
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    cache_from: goggz/ggz-server
    daemon_off: false
    dockerfile: docker/ggz-server/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: goggz/ggz-server
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: ggz-redirect-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_COMMIT_SHA:0:8} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/amd64/ggz-redirect ./cmd/ggz-redirect"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_TAG##v} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/amd64/ggz-redirect ./cmd/ggz-redirect"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.12
  commands:
  - ./release/linux/amd64/ggz-redirect --help

- name: dryrun
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    cache_from: goggz/ggz-redirect
    dockerfile: docker/ggz-redirect/Dockerfile.linux.amd64
    dry_run: true
    repo: goggz/ggz-redirect
    tags: linux-amd64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    cache_from: goggz/ggz-redirect
    daemon_off: false
    dockerfile: docker/ggz-redirect/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: goggz/ggz-redirect
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: ggz-redirect-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build-push
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_COMMIT_SHA:0:8} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm64/ggz-redirect ./cmd/ggz-redirect"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_TAG##v} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm64/ggz-redirect ./cmd/ggz-redirect"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.12
  commands:
  - ./release/linux/arm64/ggz-redirect --help

- name: dryrun
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    cache_from: goggz/ggz-redirect
    dockerfile: docker/ggz-redirect/Dockerfile.linux.arm64
    dry_run: true
    repo: goggz/ggz-redirect
    tags: linux-arm64
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    cache_from: goggz/ggz-redirect
    daemon_off: false
    dockerfile: docker/ggz-redirect/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: goggz/ggz-redirect
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: ggz-redirect-linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: build-push
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_COMMIT_SHA:0:8} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm/ggz-redirect ./cmd/ggz-redirect"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-tag
  pull: always
  image: golang:1.12
  commands:
  - "go build -v -ldflags \"-X github.com/go-ggz/ggz/version.Version=${DRONE_TAG##v} -X github.com/go-ggz/ggz/version.BuildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`\" -a -o release/linux/arm/ggz-redirect ./cmd/ggz-redirect"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - tag

- name: executable
  pull: always
  image: golang:1.12
  commands:
  - ./release/linux/arm/ggz-redirect --help

- name: dryrun
  pull: always
  image: plugins/docker:linux-arm
  settings:
    cache_from: goggz/ggz-redirect
    dockerfile: docker/ggz-redirect/Dockerfile.linux.arm
    dry_run: true
    repo: goggz/ggz-redirect
    tags: linux-arm
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    cache_from: goggz/ggz-redirect
    daemon_off: false
    dockerfile: docker/ggz-redirect/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: goggz/ggz-redirect
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/pull/**"
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: release-binary

platform:
  os: linux
  arch: amd64

steps:
- name: build-all-binary
  pull: always
  image: golang:1.12
  commands:
  - make release
  environment:
    GO111MODULE: on
  when:
    event:
    - tag

- name: deploy-all-binary
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_api_key
    files:
    - "dist/release/*"
  when:
    event:
    - tag

trigger:
  ref:
  - "refs/tags/**"

depends_on:
- testing

---
kind: pipeline
name: ggz-server-notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/ggz-server/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"

depends_on:
- ggz-server-linux-amd64
- ggz-server-linux-arm64
- ggz-server-linux-arm
- release-binary

---
kind: pipeline
name: ggz-redirect-notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: docker/ggz-redirect/manifest.tmpl
    username:
      from_secret: docker_username

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"

depends_on:
- ggz-redirect-linux-amd64
- ggz-redirect-linux-arm64
- ggz-redirect-linux-arm
- release-binary

...
