FROM alpine:3.7

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>"

EXPOSE 8080 8081 80 443

ADD bin/ggz /

ENTRYPOINT ["/ggz"]
CMD ["server"]
