FROM alpine:3.7

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>"

EXPOSE 8080 8081

ADD bin/ggz /

HEALTHCHECK --start-period=2s --interval=10s --timeout=5s \
  CMD ["/ggz", "ping"]

ENTRYPOINT ["/ggz"]
CMD ["server"]
