FROM microsoft/nanoserver:10.0.14393.1884

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="ggz-redirect" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

ADD release/ggz-redirect.exe C:/bin/ggz-redirect.exe

EXPOSE 8080

ENTRYPOINT [ ""C:\\bin\\ggz-redirect.exe"" ]
