FROM plugins/base:arm

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="ggz-redirect" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm/ggz-redirect /bin/

EXPOSE 8080

HEALTHCHECK --start-period=2s --interval=10s --timeout=5s \
  CMD ["/bin/ggz-redirect", "ping"]

ENTRYPOINT ["/bin/ggz-redirect"]
CMD ["server"]
