FROM alpine:3.7

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="ggz" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

EXPOSE 8080

ADD ../release/linux/amd64/ggz-server /bin/

HEALTHCHECK --start-period=2s --interval=10s --timeout=5s \
  CMD ["/bin/ggz-server", "ping"]

ENTRYPOINT ["/bin/ggz-server"]
CMD ["server"]
